export * from './header/Header';
export * from './profile/Profile';
export * from './services/Services';
export * from './living-room/LivingRoom';
export * from './product-preview/ProductPreview';
export * from './new-products/NewProducts';
export * from './articles/Articles';
export * from './footer/Footer';
export * from './modal/Modal.tsx';
