export * from '../pages/main-page/ui/Header.tsx';
export * from './profile/Profile';
export * from './services/Services';
export * from './living-room/LivingRoom';
export * from './product-preview/ProductPreview';
export * from './new-products/NewProducts';
export * from '../features/articles/ui/Articles.tsx';
export * from '../pages/main-page/ui/Footer.tsx';
export * from './modal/Modal.tsx';
